= Syp Projekt 2022/23



== Projektbezeichnung:
* Vorratchecker

== Projektauftraggeber:
* HTBLA Leonding, Auftraggeber: Herr Prof. Stütz,

== Kontakte:
Kontakte: David Lehner d.lehner2@students.htl-leonding.ac.at, +
Fröller Felix f.froeller@stundents.htl-leonding.ac.at, +
Anton Cao a.cao@students.htl-leonding.ac.at, +
Saydam Arda a.saydam@students.htl-leonding.ac.at

== Projekthintergrund:
* Manchmal hat man das Problem, dass man nicht weiß, was derzeit an Lebensmitteln, Gewürzen usw. zu Hause ist. Auch findet man teilweise nicht die richtigen Rabatte.

== Projektendergebnis:
* Erreicht wird eine App/Website, die den aktuellen Bestand der Lebensmittel, o.ä, ablesen, speichern, und ändern kann. Dazu soll es möglich sein, passende Prospekte auf einem Blick zu haben. Ein messbares Ergebnis könnte die Einsparung bei jeweiligen Einkäufen sein.

== Projektziel:
* Eine genaue Ablesbarkeit, wie viel von einem Produkt noch zu Hause ist. Erinnerung, wenn etwas knapp werden könnte und vorschlagen von Prospekten, welche die fehlenden Produkte zu Hause beinhalten könnten.
Messbarkeit: Wie viel Abfall gespart wurde, mittels einer Erinnerung wird der Benutzer benachrichtigt, wenn etwas abläuft. Gespartes Geld durch vorgeschlagene Angebote.


== Projektbeschreibung:
* Wir bauen das Projekt schrittweise aufbauen. Das heißt, zuerst die grundlegenden Funktionen festlegen. Danach werden die benötigten Technologien bestimmt. Darauf folgt das Design und dann der Prozess des Aufbauens.
Beim Aufbauen bauen wir zuerst das Grundgerüst d.h. Design aufgestellt und dann die restlichen Funktionen implementiert.

== Projektphasen / Meilensteine:
|===
|Phase|Meilenstein / Ergebnis|Soll-Termin
|Technologien|Bestimmung der Technologien / festgelegte Technologien|1.2.2023
|Design|Grundlegendes Design festlegen / fertiges Design, welches sich durch die komplette App durchzieht|1.3.2023
|Aufbauen|Grundgerüst fertigen / fertiger Aufbau der App ohne Funktionen|1.5.2023
|Implementation|Das Grundgerüst aus implementieren / Funktionen für die App fertigen|Ende des Schuljahres
|===

== Projektrisiken
* Zu wenig Zeit
* Komplikationen mit Technologien
* keine Möglichkeit, die richtigen Prospekte zu finden

== Projektstart
* Das Projekt wird mit Beschluss von Herrn Professor Stütz gestartet

== Projektende
* Das Projekt soll bis zum Ende des Schuljahres beendet werden.

== Projektressourcen
* Es wird nichts zusätzlich an Personal gebraucht. (Nur die 4 Mitglieder)
* An Material werden nur Rechner benötigt, die bereits jeder besitzt.
* Es kann sein, dass ein Raspberry Pi benötigt wird. Dieser muss nicht zusätzlich gekauft werden.

== Projektorganisation
* Projektleiter: David Lehner
* Projektteam: Cao Anton, Fröller Felix, Saydam Arda

== Abschluss des Projektauftrags:
* 27.10.22, Cao Anton, Fröller Felix, Lehner David, Saydam Arda

